services:
  # VAPI Demo Application - Main Service
  vapi-demo:
    build: .
    container_name: vapi-demo-app
    ports:
      - "8000:8000"
    environment:
      # VAPI Configuration (from Coolify secrets)
      - ASSISTANT_ID=${ASSISTANT_ID}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - VAPI_PRIVATE_KEY=${VAPI_PRIVATE_KEY}
      
      # App Configuration
      - CONFIG_PASSWORD=${CONFIG_PASSWORD}
      - COMPANY_NAME=${COMPANY_NAME}
      - SUPPORT_EMAIL=${SUPPORT_EMAIL}
      
      # Website & Branding
      - WEBSITE_URL=${WEBSITE_URL}
      - IMPRESSUM_URL=${IMPRESSUM_URL}
      - PRIVACY_POLICY_URL=${PRIVACY_POLICY_URL}
      - TERMS_URL=${TERMS_URL}
      - PRIMARY_COLOR=${PRIMARY_COLOR}
      - SECONDARY_COLOR=${SECONDARY_COLOR}
      - ACCENT_COLOR=${ACCENT_COLOR}
      - LOGO_URL=${LOGO_URL}
      
      # Contact Options
      - CALENDLY_LINK=${CALENDLY_LINK}
      - FACEBOOK_BUSINESS_WHATSAPP=${FACEBOOK_BUSINESS_WHATSAPP}
      
      # Redis Configuration (INTERNAL Redis Container)
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      
      # Shlink Configuration (DISABLED - use external service)
      - SHLINK_API_KEY=${SHLINK_API_KEY}
      - SHLINK_BASE_URL=${SHLINK_BASE_URL}
      
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for session management
  redis:
    image: redis:7-alpine
    container_name: vapi-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-vapi_redis_password}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-vapi_redis_password}", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
