version: '3.8'

services:
  # VAPI Demo Application
  vapi-demo:
    build: .
    container_name: vapi-demo-app
    ports:
      - "8030:8000"
    environment:
      # Redis Configuration (internal Docker Redis)
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      
      # Shlink Configuration (external or internal)
      - SHLINK_API_KEY=${SHLINK_API_KEY}
      - SHLINK_BASE_URL=${SHLINK_BASE_URL}
      
      # VAPI Configuration (set these in .env or Coolify)
      - ASSISTANT_ID=${ASSISTANT_ID}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - VAPI_PRIVATE_KEY=${VAPI_PRIVATE_KEY}
      
      # App Configuration
      - CONFIG_PASSWORD=${CONFIG_PASSWORD}
      - COMPANY_NAME=${COMPANY_NAME}
      - SUPPORT_EMAIL=${SUPPORT_EMAIL}
      
      # Optional Features
      - FACEBOOK_BUSINESS_WHATSAPP=${FACEBOOK_BUSINESS_WHATSAPP}
      - CALENDLY_LINK=${CALENDLY_LINK}
      
    # volumes:
      # - ./.env:/app/.env:ro  # DISABLED: Coolify manages environment variables
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for session management (optional - can use external)
  redis:
    image: redis:7-alpine
    container_name: vapi-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # Shlink URL Shortener - EXTERNAL SERVICE
  # Configure your external Shlink instance in .env file
  # Example: https://your-shlink-domain.com/rest/v3

volumes:
  redis_data:
    driver: local